
# header nav
# 菜单路径
menu:
  home: /
  archives: archives
  categories: /categories  
  tags: /tags
  about: /about
  search: search

# site title 
# 页面的标题
# title为空时 Hexo/_config.yml 配置有效
title: Qilingu


# author profile
# source/imgaes/
# 作者信息
# author为空时 Hexo/_config.yml 配置有效
profile: 
  logo: Gu's Blog
  author: Harry Gu
  avatar: /images/header.jpg 
  location: NanJing CN

# site favicon
# source/imgaes/
# 站点图标
favicon: /images/favicon.png

# social link
social:  
  Github: https://github.com/qilin1992/qilin1992.github.io 
  Zhihu:
  Weibo:
  Facebook:
  Twitter:
  Instagram:
  LinkedIn:
  Others:


# toc
# 文章的目录 仅识别 H1 和 H2/H3
toc:
    true

# site analytics 
# 站点访问统计
# [ analytics id ]
baidu_analytics:
  #############
google_analytics: 

# comment

# disqus(https://disqus.com/)
disqus:
  comment: fasle
  shortname: qilingu

# valine(https://github.com/xCss/Valine)
# 创建 leancloud 应用 获取 id|key 填入即可
leancloud:  
  comment: true
  app_id: cFM0eCo0CQ9xmBXmHi1eltol-gzGzoHsz
  app_key: oh9tizsnvV2vNvWgqEvoNtQO

# mob share(http://www.mob.com)
# 文章分享功能
mob_share:
  true

share_item:
- qq
- weixin
- weibo
- douban
- facebook
- twitter
#- tumblr
- google


# donate
# 捐赠功能
# source/imgaes/
donate:
  enable: false
  word: 世界美好 你也是
  wechat: /images/donate1.png
  alipay: /images/donate2.png

# mathjax 
# 渲染LateX公式
# 在post文章头部添加:
#   mathjax: true
# 即可在当前post开启mathjax
mathjax:
  enable: true
  

# footer
# 底部信息
footer:
  author: Harry Gu
  since: 2017

# busuanzi site count
# 底部访客记录
busuanzi:
  true


#theme version
version:
  0.1.7
  
search:
  path: search.xml
  field: post